a=int(input('Numarul de oua la prima gaina:'))
b=int(input('Numarul de oua la a doua gaina:'))
c=int(input('Numarul de oua la a treia gaina:'))
d=int(input('Numarul de oua la a patra gaina:'))
print("In o saptaman se obtin", 7*(a+b+c+d), "oua")